### ISSUE TITLE
app assets are not accessible behind nginx proxy on kubernetes

### ISSUE THREAD

**Issue by rvashishth** [bbonnin/pulsar-express#19]
Similar [issue on pulsar dashboard](https://github.com/apache/pulsar/issues/5623) 

I have deployed `pulsar-express` on azure kubernetes services. when loading the on browser using nginx ingress controller host name, it failed to load resources. All call to resources are made using absolute path. 

<img width="1660" alt="Screenshot 2019-11-18 at 8 12 04 PM" src="https://user-images.githubusercontent.com/6093884/69061719-ba1e8080-0a3f-11ea-9d3e-0e84f0e8ccd6.png">

here Pulsar-Express is deployed behind < https://cluster-host/pulsar-express > but all call to asset resources is not going via `/pulsar-express` uri, instead all call are made to absolute uri. https://cluster-host/_nuxt/576314c3783866ee5689.js  instead of  https://cluster-host/pulsar-express/_nuxt/576314c3783866ee5689.js

**Comment by bbonnin** [comment]
Hi,

I have made a quick fix.
The steps:
* Set the base URL you want to use: `export PE_BASE_URL=pulsar-express`
* Rebuild the docker image: `npm run docker-build` (or `docker build --build-arg BASE_URL=${PE_BASE_URL} -t pulsar-express .`)
* Run the image, for example: `docker run -it -p 3000:3000 -e PE_CONNECTION_URL=http://host.docker.internal:8080 -e PE_BASE_URL=${PE_BASE_URL} pulsar-express`

> When running the image, do not forget to set PE_BASE_URL !

HTH

**Comment by rvashishth** [comment]
I have tested this fix, there still seems some issue while loading the fonts.  
```
Refused to load the font 'data:font/woff;base64,d09KZU=' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by bbonnin-zen** [comment]
@rvashishth 
I've just pushed a config file for this problem.
Can you test and let me know if it's better ?

**Comment by rvashishth** [comment]
it didn't work for me via nginx. Though i can access the app using LoadBalancer service type. Check below the kubernetes nginx config and errors. 

```
{
  "kind": "Ingress",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "pulsar-dashboard",
      "annotations": {
      "kubernetes.io/ingress.class": "nginx",
      "nginx.ingress.kubernetes.io/rewrite-target": "/$2"
    }
  },
  "spec": {
    "rules": [
      {
        "host": “my.domain”,
        "http": {
          "paths": [
            {
              "path": "/pexpress(/|$)(.*)",
              "backend": {
                "serviceName": "pulsar-express",
                "servicePort": 3000
              }
            }
          ]
        }
      }
    ]
  }
}
```

Error remains same.

<img width="1548" alt="Screenshot 2019-12-12 at 1 53 11 PM" src="https://user-images.githubusercontent.com/6093884/70695008-ce743700-1ce6-11ea-9e70-c3a6a1a6dc85.png">

**Comment by bruno-bonnin-cbp** [comment]
In my fix, I've updated the content security policy directive.
And you should not get this error.
You have this error with the first page ?
Have you rebuilt the project before redeploying it ?

**Comment by rvashishth** [comment]
yes. i have tested with updated build.

**Comment by bruno-bonnin-cbp** [comment]
If you inspect the first page for example, have you the same values like in this image ?

![PE](https://user-images.githubusercontent.com/51698900/70732622-14da8d80-1d09-11ea-894c-96ef3e3cec03.png)
